import React from 'react';
import { Layout } from '../components/layout';

export default function Index() {
  return (
    <Layout>
      <h1>Hello from a Gatsby site!</h1>
      <p>This is a Jamstack site generated by Gatsby.</p>
    </Layout>
  );
}
